### PR TITLE
#91 enabling github actions (ci build)

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by stevesobol** [comment]
Ahhhh... I have CircleCI set up and ready to go, actually. Was planning on using CircleCI, not GitHub, for CI. I haven't added a comment to that effect to Issue https://github.com/cjwizard/cjwizard/issues/91 because I haven't had time to. This is something we should discuss, anyhow.

**Comment by spyhunter99** [comment]
well whatever you want. i thought travis ci would never go away, and it did. Stuff build into github seems unlikely to go away but who knows. never used circleci though

**Comment by stevesobol** [comment]
No one thought Travis CI was going to go away. :)

No one thought JFrog was going to turn off Bintray, either. It happens.

My choice is based on cost, because, though it's unlikely, there is always a chance that we will end up using more than our free allotment of resources. CircleCI gives you more for free than Github does, and they have a service tier specifically meant for use by OSS projects.

Not ready to make a decision yet. I'm playing around with CircleCI now. (I'm new to CircleCI too)

**Comment by stevesobol** [comment]
Closing this pull request because I'm about to set up CircleCI.

**Pull request closed without merging**
