### PR TITLE
NOJIRA remove IDE specific settings

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by stevesobol** [comment]
So it looks like we're removing Eclipse-specific files here, right?

We need to look at .gitignore too, which I'm about to do right now.

**Comment by stevesobol** [comment]
Following up to myself:

Before we merge these changes, I want to make sure .gitignore is ignoring Eclipse settings, IntelliJ settings **and** NetBeans settings.

**Comment by stevesobol** [comment]
Bite me, Github.

Seriously. How come I have absolutely no other way to contact team members?

@spyhunter99 please shoot me an email, [steve@lobosstudios.com](mailto:steve@lobosstudios.com) - we need to coordinate on open issues and pull requests.

**Comment by spyhunter99** [comment]
@stevesobol email dispatched....

**Pull request merged**
