### PR TITLE
#55 getter from a wizard page to get a reference to the current contr…

### PR DESCRIPTION
**Pull request by spyhunter99**
…oller, which will enable pages to advance themselves if needed

### CODE REVIEW

**Comment by spyhunter99** [comment]
Ping. is someone ever going to look at this? I have a deadline coming up and I need this fix in there. If this won't/can't be merged, I may end up publishing my fork of this project under a different group id.

**Comment by stevesobol** [comment]
When do you need it done? I can take a look at it this week. Still getting up to speed…

 

--

Lobos Studios | Phone: 877.919.4WEB | LobosStudios.com | Facebook.com/LobosStudios | @LobosStudios

Web Development - Mobile Development - Helpdesk/Tech Support - Computer Sales & Service

Acer Authorized Reseller - Computers, Windows and Android Tablets, Accessories

 

Steve Sobol - CEO, Senior Developer and Server Jockey

steve@LobosStudios.com

**Comment by stevesobol** [comment]
I'd like to check this out tomorrow and merge it then, if it looks good. Full day today. Let me know if that is acceptable.

**Comment by stevesobol** [comment]
Actually, I just took a look at it. Looks fine. Merging it now.

**Pull request merged**
