### PR TITLE
Fix NPE on navigation after call to visitPage()

### PR DESCRIPTION
**Pull request by mperrando**
Removed the wrong double "pop".

### CODE REVIEW

**Comment by stevesobol** [comment]
Marco,

Can you give me a little more detail about what the error is that you fixed?

Thanks
--Fearless Leader

**Comment by stevesobol** [comment]
Also, steps to reproduce the error

**Comment by mperrando** [comment]
You have simply to use the method visit in a wizard with some pages, and then press the Next and Prev buttons a couple of times to reproduce the error.
The problem is trivial and I hoped the diff was enough. 
The method visit must remove from the containers (_cancelStatuses end the others) the information of the current step, but it is performing TWO "pop" operations for every container! This removes too many things and raises NPE because the containers do not contain the correct number of steps.

**Comment by stevesobol** [comment]
Ok, thanks.

**Comment by stevesobol** [comment]
Honestly, it's not that the diff did (or didn't) have enough documentation - I am going to start requesting that everyone give the details that I requested from you because it makes the maintainers' lives easier. I don't think it was an unreasonable request.

I'm going to get this into the next release, 1.0.10, sometime this month. I'm planning on reviewing and merging it sometime this coming week, hopefully within the next couple days. I deeply appreciate your patience.

**Comment by mperrando** [comment]
No problem!
I change the commit message so to make it more clear, if you agree.

**Comment by stevesobol** [comment]
I'm not able to get my sample code to cause an exception, though I am seeing some other VERY strange behavior.

```

package test;

import com.github.cjwizard.APageFactory;
import com.github.cjwizard.StackWizardSettings;
import com.github.cjwizard.WizardContainer;
import com.github.cjwizard.WizardListener;
import com.github.cjwizard.WizardPage;
import com.github.cjwizard.WizardSettings;
import com.github.cjwizard.pagetemplates.TitledPageTemplate;

import javax.swing.JDialog;
import javax.swing.JLabel;
import java.util.List;

public class BreakMe extends JDialog {

   public static void main(String[] args) {
      // create the dialog, and show it:
      BreakMe test = new BreakMe();
      test.setVisible(true);
   }

   private BreakMe() {
   	    TestFactory factory = new TestFactory();
	   final WizardContainer wc =
			   new WizardContainer(factory,
					   new TitledPageTemplate(),
					   new StackWizardSettings());

	   wc.setForgetTraversedPath(true);

	   wc.addWizardListener(new WizardListener(){
		   @Override
		   public void onCanceled(List<WizardPage> path, WizardSettings settings) {
			   BreakMe.this.dispose();
		   }

		   @Override
		   public void onFinished(List<WizardPage> path, WizardSettings settings) {
			   BreakMe.this.dispose();
		   }

		   @Override
		   public void onPageChanged(WizardPage newPage, List<WizardPage> path) {
			   BreakMe.this.setTitle(newPage.getDescription());
		   }
	   });

	   // this is what should break things
	   wc.visitPage(factory.pageThree);

	   this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	   this.getContentPane().add(wc);
	   this.pack();
   }

   class TestFactory extends APageFactory {

   	    WizardPage pageOne = new WizardPage("One", "First Page"){
	        {
		        add(new JLabel("One!"));
	        }
        };

	   WizardPage pageTwo = new WizardPage("Two", "Second Page"){
		   {
			   add(new JLabel("Two!"));
		   }
	   };

	   WizardPage pageThree = new WizardPage("Three", "Third Page"){
		   {
			   add(new JLabel("Three!"));
		   }
		   public void rendering(List<WizardPage> path, WizardSettings settings) {
			   super.rendering(path, settings);
		   }
	   };

	   WizardPage pageFour = new WizardPage("Four", "Fourth Page"){
		   {
			   add(new JLabel("Four!"));
		   }
		   public void rendering(List<WizardPage> path, WizardSettings settings) {
			   super.rendering(path, settings);
			   setFinishEnabled(true);
			   setNextEnabled(false);
		   }

	   };

	   final WizardPage[] pages = {pageOne, pageTwo, pageThree, pageFour};

	   @Override
	    public WizardPage createPage(List<WizardPage> path, WizardSettings settings) {
		   return pages[path.size()];
	   }
   }

}
```

What am I doing wrong?

**Comment by mperrando** [comment]
Replace
```
       // this is what should break things
       wc.visitPage(factory.pageThree);
```
with
```     
       // this is what should break things
       wc.next();
       wc.next();
       wc.next();
       wc.visitPage(factory.pageThree);
       wc.prev();
       wc.prev();
       wc.prev();
```
the visit method corrupts the state of the wizard, so you must first build a state doing some next's, then you call the visit, so corrupting the state of the wizard, then doing prev's you get the `java.util.NoSuchElementException` because the visit method is popping **twice** from the containers.

**Comment by stevesobol** [comment]
OH!!!! 

I was thinking "call visitPage() and then navigate around using the buttons", which does break things, but not in the same way. Thanks.

**Comment by mperrando** [comment]
Sorry for the misunderstanding.
Having a failing test is always the best thing! 😄

**Comment by stevesobol** [comment]
Well, the positive thing is that I found that other bug, which I may not have found otherwise. It's possible your fix will fix both problems, but if not, at least it's on my radar now.

**Comment by stevesobol** [comment]
Good to go - good catch, and thank you for the fix.

**Pull request merged**
